### ISSUE TITLE
Errror when converting to SQuAD format

### ISSUE THREAD

**Issue by bvy007** [mandarjoshi90/triviaqa#5]
Hi,

I was trying the command given in https://github.com/mandarjoshi90/triviaqa/issues/3 given by mandarjoshi90. and i got the error as below: 

python -m utils.convert_to_squad_format --triviaqa_file triv
iaqa/qa/wikipedia-dev.json --squad_file squad --wikipedia_dir triviaqa/evidence/wikipedia/ --web_dir triviaqa/evidence/web/
  2%|█▎                                                                                 | 230/14229 [00:01<01:29, 156.84it/s]
Traceback (most recent call last):
  File "C:\Users\Vamshi\Anaconda3\envs\PythonGPU\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Vamshi\Anaconda3\envs\PythonGPU\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Vamshi\__Workspace__\triviaqa-master\triviaqa-master\utils\convert_to_squad_format.py", line 110, in <module>

    convert_to_squad_format(args.triviaqa_file, args.squad_file)
  File "C:\Users\Vamshi\__Workspace__\triviaqa-master\triviaqa-master\utils\convert_to_squad_format.py", line 67, in convert_t
o_squad_format
    text = get_text(qad, qad['Source'])
  File "C:\Users\Vamshi\__Workspace__\triviaqa-master\triviaqa-master\utils\convert_to_squad_format.py", line 12, in get_text
    return utils.utils.get_file_contents(local_file, encoding='utf-8')
  File "C:\Users\Vamshi\__Workspace__\triviaqa-master\triviaqa-master\utils\utils.py", line 10, in get_file_contents
    with open(filename, encoding=encoding) as f:
OSError: [Errno 22] Invalid argument: "triviaqa/evidence/wikipedia/Who's_on_First?.txt"

Can someone help me in resolving it ?

**Comment by bvy007** [comment]
It got resolved by renaming the file names in json file. OS did not take the '?'  or ':' chars in filename. Manually edited them using error files
